// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAkA0Rdw4OnffgzVnWMVP-UDidm6LVL-A',
    appId: '1:594588918362:web:f89cf1bf47350905b1ee63',
    messagingSenderId: '594588918362',
    projectId: 'crud-65887',
    authDomain: 'crud-65887.firebaseapp.com',
    storageBucket: 'crud-65887.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbW7wkFRBlPFK-rFZq3nBF7sHFVyQBJLI',
    appId: '1:594588918362:android:c5d685c975e65895b1ee63',
    messagingSenderId: '594588918362',
    projectId: 'crud-65887',
    storageBucket: 'crud-65887.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtrgfLruBAYye75kt5168XKI2aX4Vi7V8',
    appId: '1:594588918362:ios:64129ce8c27f909db1ee63',
    messagingSenderId: '594588918362',
    projectId: 'crud-65887',
    storageBucket: 'crud-65887.appspot.com',
    iosBundleId: 'com.example.crud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtrgfLruBAYye75kt5168XKI2aX4Vi7V8',
    appId: '1:594588918362:ios:9a4ee11d427b2912b1ee63',
    messagingSenderId: '594588918362',
    projectId: 'crud-65887',
    storageBucket: 'crud-65887.appspot.com',
    iosBundleId: 'com.example.crud.RunnerTests',
  );
}
